### ISSUE TITLE
No results for GND subject queries

### ISSUE THREAD

**Issue by hornmo** [lobid/lodmill#520] opened 2014-07-31 12:34 UTC
Currently, queries for subjects via id return no results:

http://lobid.org/subject?format=full&id=1706733-9 (example from http://lobid.org/api)

http://lobid.org/subject?format=full&id=4030329-9
http://lobid.org/subject?format=full&id=4010877-6

 Persons, however, are still available:

http://lobid.org/subject?format=full&id=114454442

**Comment by dr0i** [comment] 2015-06-30 09:44
Presumably the cause is an outdated index profile. I update this profile and will reindex, we'll see tomorrow if this fixes the issue.

**Comment by dr0i** [comment] 2015-07-01 07:35
Deployed to production. @acka47 please approve nonetheless.

**Comment by acka47** [comment] 2015-07-01 08:01
+1. Closing.

**Closed by acka47** 2015-07-01 08:01 UTC
Labels: review
