### ISSUE TITLE
Missing subfield `d` (birth/death date) for person subjects

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#771] opened 2015-12-18 14:16 UTC
From https://github.com/lobid/lodmill/issues/766#issuecomment-165767182.

Example [HT016671946](http://lobid.org/resource?id=HT016671946&format=source) (snippet):

```xml
<datafield tag="902" ind1="-" ind2="1">
<subfield code="p">Jérôme</subfield>
<subfield code="c">Westfalen, König</subfield>
<subfield code="d">1784-1860</subfield>
<subfield code="9">(DE-588)118557432</subfield>
</datafield>
```

Current JSON:

```javascript
{
    "@id" : "http://d-nb.info/gnd/118557432",
    "preferredName" : "Jérôme, Westfalen, König",
    "preferredNameForThePerson" : "Jérôme, Westfalen, König"
  }
```

**Comment by dr0i** [comment] 2016-02-12 13:56
Once we had the birth/death dates included in the data. We had a discussion about it, see https://github.com/hbz/lobid/issues/244, and removed them . What to do now? Try to provide an extra field under the GND resource?

**Comment by jschnasse** [comment] 2016-02-12 14:10
+1 for the extra field, like shown in gnd rdf http://d-nb.info/gnd/118557432/about/lds

**Comment by acka47** [comment] 2016-02-12 15:12
> Once we had the birth/death dates included in the data. We had a discussion about it, see https://github.com/hbz/lobid/issues/244, and removed them 

The discussion in https://github.com/hbz/lobid/issues/244 was about birth dates for contributors. This is about birth dates for person as subjects. As we can easily separate them in the source data we should leave out birth dates for the first but add them to the second. No need for an extra field...

**Comment by dr0i** [comment] 2016-02-12 15:15
What's with the proposal of @jschnasse ? I like that it separate things, and its even way easier to transform the data into that structure.

**Comment by acka47** [comment] 2016-02-12 19:02
Thinking about it you are both right to have it in a separate field for API 2.0. The question is whether we should do this for all subfields and, thus, making our data more MARCy...

**Comment by dr0i** [comment] 2016-02-15 08:08
Deployed , see e.g. http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT016671946. Note that the birth/death dates are deliberately only added to persons which are subjects.

**Comment by acka47** [comment] 2016-02-16 13:40
Looks good – for persons a subjects. But I still think this can be improved. (Sorry.)

> Note that the birth/death dates are deliberately only added to persons which are subjects.

I think it would be ok and make sense to also deliver birth dates of authors via the API. What customers asked for was not to show them in the UI – which can easily be implemented as long as the information is in seperate fields.

**Comment by dr0i** [comment] 2016-02-16 14:01
Now I agree that all things can be improved. And if you are willing to say " person subjects" (as this issues title actually is) are herewith be properly treated ...

**Comment by dr0i** [comment] 2016-02-16 14:02
s/separate/separate

**Comment by acka47** [comment] 2016-02-16 14:13
> Now I agree that all things can be improved. And if you are willing to say " person subjects" (as this issues title actually is) are herewith be properly treated ...

I am tempted to change the issue's title back...However, +1 and we'll get on with it...

**Comment by dr0i** [comment] 2016-02-16 14:17
you have a point there, but thx!

**Comment by fsteeg** [comment] 2016-02-17 14:15
I'm assigned to display the life dates in NWBib? So for http://test.lobid.org/nwbib/HT016671946, 'Schlagwörter' should contain `Jérôme, Westfalen, König (1784-1860)`?

**Comment by acka47** [comment] 2016-02-17 14:30
> I'm assigned to display the life dates in NWBib? So for http://test.lobid.org/nwbib/HT016671946, 'Schlagwörter' should contain `Jérôme, Westfalen, König (1784-1860)`?

Yes, but it doesn't have that much priority.

**Comment by fsteeg** [comment] 2016-03-09 14:01
The current transformation for this in subject chains looks wrong to me:

http://nwbib.de/HT016671946 -> `Jérôme (1784-1860), Westfalen, König`

As for the subject part, shouldn't it be `Jérôme, Westfalen, König (1784-1860)`?

I seem to remember that it was like that before, could this be a regression @dr0i?

**Comment by fsteeg** [comment] 2016-03-09 14:20
Deployed the nwbib part to staging: http://test.nwbib.de/HT016671946

If only birth is given: http://test.nwbib.de/HT018866836

**Comment by dr0i** [comment] 2016-03-09 14:48
> I seem to remember that it was like that before, could this be a regression @dr0i?

No I think it was ever deliberately so: "Name (birth dates), title etc.)".
For me it also feels better to write the time period behind the person, because its the person's life dates. If it's written at the end like in `Jérôme, Westfalen, König (1784-1860)` I would assume that he was king for that period (well, unlikely semantically but structurally so). No ?

**Comment by acka47** [comment] 2016-03-09 15:20
+1 for NWBib and the subject chains. (It doesn't make sense to put more work in the `subjectChain` field as we will get rid of it anyway with API 2.0.)

**Closed** 2016-03-09 16:06 UTC
Labels: deploy, nwbib-launch
