### ISSUE TITLE
dct:title of bibo:Journal not generated correctly for RDA records

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#762] opened 2015-12-09 08:58 UTC
[Edit: Reported by edoweb customers on 2015-12-02.]

See e.g. http://lobid.org/resource/HT016320444 (pre-RDA record) vs. http://lobid.org/resource/HT018819975 (RDA record).

Frrom the [source of HT016320444](http://lobid.org/resource?id=HT016320444&format=source):

```xml
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">Q</subfield>
</datafield>
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">I</subfield>
  <subfield code="a">Öffentliche Klärschlammentsorgung ...</subfield>
  <subfield code="n">Elektronische Ressource</subfield>
</datafield>
<datafield tag="310" ind1="-" ind2="1">
  <subfield code="a">Statistische Berichte Rheinland-Pfalz / Q / 1</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="1">
  <subfield code="a">Statistische Berichte Rheinland-Pfalz</subfield>
</datafield>
```

As you can see, the field 310 contains information that is already present in 331 and fields 085. I guess, witht he switch to RDA they decided to get rid of this redundancy (which is a good thing, I think).

In the relevant parts of the RDA record's [source (HT018819975)](http://lobid.org/resource?id=HT018819975&format=source) 310 is missing:

```xml
<controlfield tag="030">a||dr||||||27</controlfield>
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">O</subfield>
</datafield>
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">II</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="1">
  <subfield code="a">Statistische Berichte</subfield>
</datafield>
```

Somehow we will have to generate a correct `dct:title` both for pre-RDA and for RDA journal records

**Comment by acka47** [comment] 2015-12-09 09:12
The [relevant part of the current morph](https://github.com/lobid/lodmill/blob/b37d5fad2f0b2402b4d827e9bcfbf47066d891da/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L449-L491) currently only take into account 310, 331 and 333 for generating dct:title and work something like this:

- They apply to _all_ types of resources
- `dct:title` is generated from 310 if it existsts. 331 and 333 are used as `otherTitleInformation`.
- If 310 doesn't exist, 331 is used for `dct:title` and if 331 doesn't exist, we use 333.

I see different possibilities for solving this issue:

1. We could do a Journal-specific transformationto for `dct:title` by concatenating 085s to 331. 
2. We could adjust the current global transformation by
a) adding a rule "concatenate 085 when 331 is used for generating the title"
b) adding a rule "if 085 exists, create `dct:title` by concatenating 331 and 085".

Probably 2.b) would be the easiest solution but it would mean that the title for bibo:Journals are generated differently pre- and post-RDA. 

What do you thin, @dr0i?

**Comment by acka47** [comment] 2015-12-09 15:48
Our colleague Stephani pointed to the fact that the information to be concatenated to 331 in RDA records should be taken from `360` (which seems to be redundant to 85 :-/.

**Comment by dr0i** [comment] 2015-12-10 10:17
As both your examples have also `360` and this field is even mentioned in the mb-dnb definition (whereas `085` is not mentioned) I would suggest to substitute `085` with `360` and execute your propoal "2.a", resulting in 

> We could adjust the current global transformation by a) adding a rule "concatenate 360 when 331 is used for generating the title"

Or do we need the more detailed subfields differentiating `085` from `360`? Or, not sure about that, is it even possible that `085` exists while `360` does not?

**Comment by acka47** [comment] 2015-12-10 11:00
Having looked at the data again, using `360` is not feasible as it results in `title` fields that aren't requested by stakeholders. See for example [HT018785916](source)]():

```xml
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">K</subfield>
</datafield>
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">VIII</subfield>
</datafield>
<datafield tag="085" ind1="x" ind2="1">
  <subfield code="l">1</subfield>
  <subfield code="a">Einrichtungen für ältere Menschen in Bayern ... und ambulant betreute Wohngemeinschaften in Bayern ...</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="1">
  <subfield code="a">Statistische Berichte</subfield>
</datafield>
<datafield tag="360" ind1="-" ind2="1">
  <subfield code="a">K</subfield>
</datafield>
<datafield tag="360" ind1="-" ind2="1">
  <subfield code="a">VIII</subfield>
</datafield>
<datafield tag="360" ind1="-" ind2="1">
  <subfield code="a">1, Einrichtungen für ältere Menschen in Bayern ... und ambulant betreute Wohngemeinschaften in Bayern ...</subfield>
</datafield>
```

Generating the title from `331`+`085.l` the structure provided by subfields enables to provide what stakeholders expect: `Statistische Berichte / K / VIII / 1`
Using `331`+`360` we are missing structure an can only provide `Statistische Berichte / K / VIII / 1, Einrichtungen für ältere Menschen in Bayern ... und ambulant betreute Wohngemeinschaften in Bayern ...` – which stakeholders would not be happy with.

Thus, we will do it as I said in https://github.com/lobid/lodmill/issues/762#issuecomment-163157200, 2. a) using only subfield `l` of `085`: "concatenate 085.l with "space-slash-space" (` / `) when 331 is used for generating the title"

**Comment by dr0i** [comment] 2015-12-14 07:45
Deployed to staging.

**Comment by dr0i** [comment] 2015-12-14 07:48
Removed the `bug` label because it's no bug. Everything worked as intended. It's rather a `feature request`, an `enhancement`.

**Comment by acka47** [comment] 2015-12-14 09:26
+1

**Comment by dr0i** [comment] 2015-12-14 09:33
Deployed to production, closing.

**Closed by dr0i** 2015-12-14 09:33 UTC

**Comment by acka47** [comment] 2016-02-16 12:03
This is a sub-issue of https://github.com/hbz/lobid/issues/161.
